apiVersion: v1
kind: Pod
metadata:
  name: details
  labels:
    app: details
spec:
  containers:
    - name: details
      image: localhost:5001/details:1.0
      readinessProbe:
        initialDelaySeconds: 15
        periodSeconds: 15
        exec:
          command:
            - cat
      livenessProbe:
        httpGet:
          path: /health
          port: 9080
        initialDelaySeconds: 15
        periodSeconds: 15
      env:
        - name: SERVICE_VERSION
          value: "v1"
        - name: ENABLE_EXTERNAL_BOOK_SERVICE
          value: "false"
      ports:
        - containerPort: 9080
