apiVersion: v1
kind: Pod
metadata:
  name: mysql
spec:
  containers:
    - image: localhost:5001/mysql:1.0
      name: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
      ports:
        - containerPort: 3306
