apiVersion: v1
kind: Pod
metadata:
  name: productpage
  labels:
    app: productpage
spec:
  containers:
    - image: localhost:5001/productpage:1.0
      name: productpage
      env:
        - name: FLOOD_FACTOR
          value: "0"
      ports:
        - containerPort: 9080
      readinessProbe:
        initialDelaySeconds: 15
        periodSeconds: 15
        exec:
          command:
            - cat
      livenessProbe:
        httpGet:
          path: /health
          port: 9080
        initialDelaySeconds: 15
        periodSeconds: 15