apiVersion: v1
kind: Service
metadata:
  name: ratings
spec:
  selector:
    app: ratings-v2 ### Pour deployer des ratings-v1, il suffit de changer ratings-v2 en ratings-v1 ici
  ports:
    - protocol: TCP
      port: 9080
      targetPort: 9080