apiVersion: v1
kind: Pod
metadata:
  name: ratings
  labels:
    app: ratings
spec:
  containers:
    - image: localhost:5001/ratings:1.0
      name: ratings
      env:
        - name: SERVICE_VERSION
          value: "v1"
      ports:
        - containerPort: 9080