###apiVersion: v1
###kind: Pod
###metadata:
###  name: ratings
###  labels:
###    app: ratings
###spec:
###  containers:
###   - image: localhost:5001/ratings:1.0
###      name: ratings
###      env:
###        - name: SERVICE_VERSION
###          value: "v1"
###      ports:
###        - containerPort: 9080


apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings
  labels:
    app: ratings
spec:
  replicas: 5
  selector:
    matchLabels:
      app: ratings
  template:
    metadata:
      labels:
        app: ratings
    spec:
      containers:
        - image: docker.io/istio/examples-bookinfo-mongodb:1.16.2
          name: ratings
          env:
            - name: SERVICE_VERSION
              value: "v2"
            - name: DB_TYPE
              value: "mysql"
          ports:
            - containerPort: 9080