apiVersion: v1
kind: Pod
metadata:
  name: reviews
  labels:
    app: reviews
spec:
  containers:
    - image: docker.io/istio/examples-bookinfo-reviews-v1:1.16.2
      name: reviews
      ports:
        - containerPort: 9080
      readinessProbe:
        initialDelaySeconds: 15
        periodSeconds: 15
        exec:
          command:
            - cat
      livenessProbe:
        httpGet:
          path: /health
          port: 9080
        initialDelaySeconds: 15
        periodSeconds: 15